# Generated by Django 3.2.5 on 2021-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
