# Generated by Django 3.2.5 on 2021-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210730_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies')], max_length=10),
        ),
    ]
